blog/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    # path('article_list', views.article_list, name='list'),
    path('category/<int:pk>', views.category_list, name='category'),
    path('contactus', views.contactus, name='contactus'),
    path('articlelist', views.ArticleListView.as_view(), name='list_view'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<slug:slug>', views.article_detail, name='detail'),
    path('search/', views.search, name='search'),
    
    path('send_message/', views.MessageView.as_view(), name='send_message'),
]

stand_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from stand_blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/sidebar.html
{% load static %}
<div class="sidebar">
    <div class="row">
        <div class="col-lg-12">
            <div class="sidebar-item search">
                <form id="search_form" name="gs" method="GET" action="{% url 'home:search' %}">
                    <input type="text" name="q" class="searchText" placeholder="type to search..."
                           autocomplete="on">
                </form>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="sidebar-item recent-posts">
                <div class="sidebar-heading">
                    <h2>Recent Posts</h2>
                </div>
                <div class="content">
                    <ul>

                        {% for articles in recent_article %}
                            <li><a href="{% url 'home:detail' articles.pk %}">
                                <h5>{{ articles.title }}</h5>
                                <span>{{ articles.created_at }}</span>
                            </a></li>

                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="sidebar-item categories">
                <div class="sidebar-heading">
                    <h2>Categories</h2>
                </div>
                <div class="content">
                    <ul>
                        {% for cat in category %}
                            <li><a href="{% url 'post:category' cat.pk %}">- {{ cat.title }}</a></li>

                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="sidebar-item tags">
                <div class="sidebar-heading">
                    <h2>Tag Clouds</h2>
                </div>
                <div class="content">
                    <ul>
                        <li><a href="#">Lifestyle</a></li>
                        <li><a href="#">Creative</a></li>
                        <li><a href="#">HTML5</a></li>
                        <li><a href="#">Inspiration</a></li>
                        <li><a href="#">Motivation</a></li>
                        <li><a href="#">PSD</a></li>
                        <li><a href="#">Responsive</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>