account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
    path('edit', views.user_edit, name='edit'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    # path('article_list', views.article_list, name='list'),
    path('category/<int:pk>', views.category_list, name='category'),
    path('contactus', views.contactus, name='contactus'),
    path('articlelist', views.ArticleListView.as_view(), name='list_view'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<slug:slug>', views.article_detail, name='detail'),
    path('search/', views.search, name='search'),
    
    path('send_message/', views.MessageView.as_view(), name='send_message'),
]

stand_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from stand_blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load filter %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link
        href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
        rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
    <!--

    TemplateMo 551 Stand Blog

    https://templatemo.com/tm-551-stand-blog

    -->
</head>

<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">

                <a class="navbar-brand" href="index.html">
                    <h2>Stand Blog<em>.</em></h2>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item {% if request.resolver_match.url_name == 'index' %}active {% endif %}">
                            <a class="nav-link" href="{% url 'home:index' %}">HOME
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " href="about.html">ABOUT US</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'list' %}active {% endif %}">
                            <a class="nav-link" href="{% url 'post:list_view' %}">ARTICLE LIST</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">article Details</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'contactus' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'post:contactus' %}">CONTACT US</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'logout' %}active {% endif %}">
                            {% if request.user.is_authenticated %}
                            <a class="nav-link btn-outline-danger " href="{% url 'account:logout' %}">logout</a>

                        </li>
                        <li>
                            <a class="nav-link" href="">{{ request.user.username }}</a>
                        <li>
                            {% if user.profile.profile_picture %}
                            <img src="{{ user.profile.profile_picture.url }}" width="30px" height="30px"
                                style="border-radius: 100%" alt="">
                        </li>
                        {% else %}
                        <img src="{% static 'images/icons/images.png' %}" width="30px" height="30px"
                            style="border-radius: 100%" alt="">
                        {% endif %}

                        {% else %}
                        <a class="nav-link" href="{% url 'account:login' %}">login</a>
                        <li>

                            <a class="nav-link" href="{% url 'account:register' %}">register</a>
                            
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    {% block main %}

    {% endblock %}




    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="social-icons">
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Behance</a></li>
                        <li><a href="#">Linkedin</a></li>
                        <li><a href="#">Dribbble</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <p>Copyright 2020 Stand Blog Co.

                            | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Additional Scripts -->
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/owl.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/isotope.js' %}"></script>
    <script src="{% static 'js/accordions.js' %}"></script>

    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) {                   //declaring the array outside of the
            if (!cleared[t.id]) {                      // function makes it static and global
                cleared[t.id] = 1;  // you could use true and false, but that's more typing
                t.value = '';         // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>

</body>

</html>